#!/usr/bin/python3
def raise_exception_msg(message=""):
    try:
        print(c)
    except NameError:
        print(message)
